FROM python:3.7-slim

WORKDIR '/app'

# install dependencies
COPY requirements_flask.txt .
RUN pip install -r requirements_flask.txt
# install module
COPY setup.py .
RUN python setup.py develop

# mount relevant directories
COPY ./flask ./flask
COPY ./telegram ./telegram
COPY ./src ./src

EXPOSE 5000

CMD cd /app/flask && flask run --host 0.0.0.0