FROM python:3.7-slim

WORKDIR '/app'

# install dependencies
COPY requirements_flask.txt .
RUN pip install -r requirements_flask.txt
# install module
COPY setup.py .
RUN python setup.py develop

# mount relevant directories
COPY ./flask .

EXPOSE 5000

CMD export FLASK_APP=index.py && export FLASK_ENV=development && flask run --host 0.0.0.0